// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Commander = (function(_super) {

    __extends(Commander, _super);

    function Commander(row, col, enemy) {
      var charSpriteSheet, spriteSheet, stats;
      this.row = row;
      this.col = col;
      this.enemy = enemy != null ? enemy : false;
      spriteSheet = 'img/units/commander.png';
      if (this.enemy) {
        spriteSheet = 'img/units/commanderEnemy.png';
      }
      charSpriteSheet = new SpriteSheet(spriteSheet, [
        {
          length: 1,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 1,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 1,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 1,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 8,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 8,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 8,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 8,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }
      ]);
      stats = {
        name: "Commander",
        hp: 10,
        moveRange: 8,
        evasion: 0.1,
        skill: 4,
        cost: 99
      };
      Commander.__super__.constructor.call(this, charSpriteSheet, stats, null, null, 'img/units/commanderProfile.png', this.row, this.col, this.enemy);
    }

    Commander.prototype.setRow = function(r) {
      return this.row = r;
    };

    Commander.prototype.init = function() {
      Commander.__super__.init.call(this);
      return this.equip(Assets.longSword);
    };

    return Commander;

  })(Unit);

}).call(this);
