// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Knight = (function(_super) {

    __extends(Knight, _super);

    function Knight(row, col, enemy) {
      var charSpriteSheet, spriteSheet, stats;
      this.row = row;
      this.col = col;
      this.enemy = enemy != null ? enemy : false;
      spriteSheet = 'img/units/knight.png';
      if (this.enemy) {
        spriteSheet = 'img/units/knightEnemy.png';
      }
      charSpriteSheet = new SpriteSheet(spriteSheet, [
        {
          length: 11,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 11,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 11,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 11,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 10,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 10,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 10,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 10,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 12,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 12,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 12,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 12,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 5,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 5,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 5,
          cellWidth: 64,
          cellHeight: 81
        }, {
          length: 5,
          cellWidth: 64,
          cellHeight: 81
        }
      ]);
      stats = {
        name: "Knight",
        hp: 8,
        moveRange: 12,
        evasion: 0.1,
        skill: 2,
        cost: 4
      };
      Knight.__super__.constructor.call(this, charSpriteSheet, stats, null, null, 'img/units/knightProfile.png', this.row, this.col, this.enemy);
    }

    Knight.prototype.setRow = function(r) {
      return this.row = r;
    };

    Knight.prototype.init = function() {
      this.cfg = [7, 24, 15, 5];
      Knight.__super__.init.call(this);
      return this.equip(Assets.lightSpear);
    };

    return Knight;

  })(Unit);

}).call(this);
