// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Soldier = (function(_super) {

    __extends(Soldier, _super);

    function Soldier(row, col, enemy) {
      var charSpriteSheet, spriteSheet, stats;
      this.row = row;
      this.col = col;
      this.enemy = enemy != null ? enemy : false;
      spriteSheet = 'img/units/soldier.png';
      if (this.enemy) {
        spriteSheet = 'img/units/soldierEnemy.png';
      }
      charSpriteSheet = new SpriteSheet(spriteSheet, [
        {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 4,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 3,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 3,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 3,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 3,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }, {
          length: 2,
          cellWidth: 64,
          cellHeight: 64
        }
      ]);
      stats = {
        name: "Soldier",
        hp: 6,
        moveRange: 8,
        evasion: 0.1,
        skill: 1,
        cost: 1
      };
      Soldier.__super__.constructor.call(this, charSpriteSheet, stats, null, null, 'img/units/soldierProfile.png', this.row, this.col, this.enemy);
    }

    Soldier.prototype.setRow = function(r) {
      return this.row = r;
    };

    Soldier.prototype.init = function() {
      this.cfg = [5, 7, 7, 5];
      Soldier.__super__.init.call(this);
      return this.equip(Assets.sword);
    };

    return Soldier;

  })(Unit);

}).call(this);
