// Generated by CoffeeScript 1.4.0
(function() {

  window.Agent = (function() {

    function Agent() {
      this.units = [];
    }

    Agent.prototype.addUnit = function(unit) {
      this.units.push(unit);
      return unit.belongsTo = this;
    };

    Agent.prototype.resetTokens = function() {
      var unit, _i, _len, _ref, _results;
      _ref = this.units;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        unit.moveTokens = 1;
        _results.push(unit.actionTokens = 1);
      }
      return _results;
    };

    Agent.prototype.removeUnit = function(unit) {
      return this.units.remove(unit);
    };

    return Agent;

  })();

}).call(this);
