// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Armor = (function(_super) {

    __extends(Armor, _super);

    function Armor(stats, passiveAbilitiesList, iconFile) {
      this.stats = stats != null ? stats : {
        name: name,
        cost: 0,
        defence: 0
      };
      this.passiveAbilitiesList = passiveAbilitiesList;
      this.iconFile = iconFile;
      Armor.__super__.constructor.call(this);
    }

    return Armor;

  })(Component);

}).call(this);
