// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Audios = (function(_super) {

    __extends(Audios, _super);

    function Audios() {
      Common.audios = this;
      this.init();
    }

    Audios.prototype.init = function() {
      this.switching = new Audio("audio/switch.mp3");
      this.hurt = new Audio("audio/hurt.wav");
      this.start = new Audio("audio/start.mp3");
      this.bgMusic = new Audio("audio/battleMusic.mp3");
      return this.bgMusic.addEventListener('ended', (function() {
        return this.bgMusic.play();
      }).bind(this));
    };

    return Audios;

  })(Component);

}).call(this);
