// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BFObject = (function(_super) {

    __extends(BFObject, _super);

    function BFObject(sprite, width, height) {
      this.sprite = sprite;
      this.width = width != null ? width : 1;
      this.height = height != null ? height : 1;
      BFObject.__super__.constructor.call(this);
      this.anchorY = 0;
      this.loaded = false;
      this.init();
    }

    BFObject.prototype.init = function() {
      this.addListener('spriteImageLoaded', this.onSpriteImageLoaded.bind(this));
      return this.addChild(this.sprite);
    };

    BFObject.prototype.onSpriteImageLoaded = function(evt) {
      if (this.loaded || (!this.sprite.hasSpriteSheet(evt.target))) {
        return;
      }
      evt = {
        type: 'bfObjectReady',
        origin: this,
        target: this
      };
      this.dispatchEvent(evt);
      return this.loaded = true;
    };

    return BFObject;

  })(Component);

}).call(this);
