// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Commander = (function(_super) {

    __extends(Commander, _super);

    function Commander(charSpriteSheet, stats, onTile, iconFile) {
      this.charSpriteSheet = charSpriteSheet;
      this.stats = stats;
      this.onTile = onTile;
      this.iconFile = iconFile;
      Commander.__super__.constructor.call(this, this.charSpriteSheet, this.stats, this.onTile, this.iconFile);
    }

    return Commander;

  })(Unit);

}).call(this);
