// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Player = (function(_super) {

    __extends(Player, _super);

    function Player() {
      this.initiativePoints = 1;
      Player.__super__.constructor.call(this);
    }

    return Player;

  })(Agent);

}).call(this);
