// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Weapon = (function(_super) {

    __extends(Weapon, _super);

    function Weapon(stats, passiveAbilitiesList, iconFile) {
      if (stats == null) {
        stats = {
          name: name,
          cost: 0,
          range: 0,
          power: 0,
          parry: 0,
          type: 'sword'
        };
      }
      this.passiveAbilitiesList = passiveAbilitiesList;
      this.iconFile = iconFile;
      this.stats = {
        name: '',
        cost: 0,
        range: 0,
        power: 0,
        parry: 0,
        type: 'sword'
      };
      $.extend(this.stats, stats);
    }

    Weapon.prototype.getRange = function() {
      return this.stats.range;
    };

    Weapon.prototype.getParry = function() {
      return this.stats.parry;
    };

    return Weapon;

  })(Component);

}).call(this);
