// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Dialog = (function(_super) {

    __extends(Dialog, _super);

    function Dialog(panelPosition, panelSize, state) {
      this.panelPosition = panelPosition;
      this.panelSize = panelSize;
      this.state = state;
      Dialog.__super__.constructor.call(this, this.panelPosition.x, this.panelPosition.y, this.panelSize.w, this.panelSize.h);
      this.init();
    }

    Dialog.prototype.init = function() {
      this.turn = "A";
      this.indexA = 0;
      this.indexB = 0;
      this.dialogA = ["Hi", "How are you?", "Not Bad either", ""];
      this.dialogB = ["Hi", "Not Bad. you?", "Not Bad", "", ""];
      this.textA;
      this.textB;
      this.personA = new Coffee2D.Image('img/personA.jpg');
      this.personA.setSize(150, 200);
      this.personA.setPosition(600, 300);
      this.addChild(this.personA);
      console.log(this.personA);
      this.personB = new Coffee2D.Image('img/personB.jpg');
      this.personB.setSize(150, 200);
      this.personB.setPosition(50, 300);
      this.addChild(this.personB);
      console.log(this.personA);
      this.addButton(20, 550, 130, 65, {
        normal: 'img/buttons/prev.png',
        onhover: 'img/buttons/prevH.png'
      }, (function() {
        console.log('clicked');
        return Common.game.startBattle();
      }).bind(this));
      this.addButton(670, 550, 130, 65, {
        normal: 'img/buttons/next.png',
        onhover: 'img/buttons/nextH.png'
      }, (function() {
        console.log('clicked');
        return this.next();
      }).bind(this));
      return this.addButton(700, 620, 70, 30, {
        normal: 'img/buttons/skip.png',
        onhover: 'img/buttons/skipH.png'
      }, (function() {
        console.log('clicked');
        return Common.game.startBattle();
      }).bind(this));
    };

    Dialog.prototype.next = function() {
      if (this.turn === "A") {
        this.removeChild(this.textA);
        console.log('text', this.dialogA);
        this.textA = new Coffee2D.Text(this.dialogA[this.indexA], 'red', '30px Arial');
        this.textA.setPosition(100, 100);
        this.addChild(this.textA);
        this.indexA += 1;
        return this.turn = "B";
      } else {
        this.removeChild(this.textB);
        console.log('text', this.dialogB);
        this.textB = new Coffee2D.Text(this.dialogB[this.indexB], 'red', '30px Arial');
        this.textB.setPosition(300, 100);
        this.addChild(this.textB);
        this.indexB += 1;
        return this.turn = "A";
      }
    };

    Dialog.prototype.displayDialog = function() {
      if (this.turn === "A") {
        return this.removeChild(this.textA);
      }
    };

    Dialog.prototype.addButton = function(x, y, w, h, icon, onclick) {
      var button, buttonH, rec;
      button = new Coffee2D.Image(icon.normal);
      button.setSize(w, h);
      button.setPosition(0, 0);
      buttonH = new Coffee2D.Image(icon.onhover);
      buttonH.setSize(w, h);
      buttonH.setPosition(0, 0);
      buttonH.hide();
      rec = new Rect(x, y, w, h);
      console.log(this.rec);
      rec.color = "rgba(0,0,0,0)";
      rec.addChild(button);
      rec.addChild(buttonH);
      this.addListener('mouseMove', (function(evt) {
        if (rec.isPointInside(evt.x, evt.y)) {
          return buttonH.show();
        } else {
          return buttonH.hide();
        }
      }).bind(this));
      button.addListener('click', onclick);
      return this.addChild(rec);
    };

    return Dialog;

  })(Component);

}).call(this);
