// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Help = (function(_super) {

    __extends(Help, _super);

    function Help(panelPosition, panelSize, state) {
      this.panelPosition = panelPosition;
      this.panelSize = panelSize;
      this.state = state;
      Help.__super__.constructor.call(this, this.panelPosition.x, this.panelPosition.y, this.panelSize.w, this.panelSize.h);
      this.bg = new Coffee2D.Image('img/help.png');
      this.bg.setSize(this.size.w, this.size.h);
      this.bg.setPosition(0, 0);
      this.selected;
      this.addChild(this.bg);
      this.addButton((this.size.w - 200) / 2, 560, 130, 65, {
        normal: 'img/buttons/menu.png',
        onhover: 'img/buttons/menuH.png'
      }, (function() {
        Common.game.reset();
        return Common.game.startMain();
      }).bind(this));
    }

    Help.prototype.addButton = function(x, y, w, h, icon, onclick) {
      var button, buttonH, rec;
      button = new Coffee2D.Image(icon.normal);
      button.setSize(w, h);
      button.setPosition(0, 0);
      buttonH = new Coffee2D.Image(icon.onhover);
      buttonH.setSize(w, h);
      buttonH.setPosition(0, 0);
      buttonH.hide();
      rec = new Rect(x, y, w, h);
      rec.color = "rgba(0,0,0,0)";
      rec.addChild(button);
      rec.addChild(buttonH);
      this.addListener('mouseMove', (function(evt) {
        if (rec.isPointInside(evt.x, evt.y)) {
          buttonH.show();
          if (this.selected !== button) {
            return this.selected = button;
          }
        } else {
          this.selected = null;
          return buttonH.hide();
        }
      }).bind(this));
      button.addListener('click', onclick);
      return this.addChild(rec);
    };

    return Help;

  })(Component);

}).call(this);
