(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Main = (function(_super) {

    __extends(Main, _super);

    function Main(panelPosition, panelSize, state) {
      this.panelPosition = panelPosition;
      this.panelSize = panelSize;
      this.state = state;
      Main.__super__.constructor.call(this, this.panelPosition.x, this.panelPosition.y, this.panelSize.w, this.panelSize.h);
      this.logo = new Coffee2D.Image('img/logo.png');
      this.logo.setSize(this.size.w * 0.8, this.size.h * 0.3);
      this.logo.setPosition(this.size.w * 0.2 / 2, 0);
      this.addChild(this.logo);
      this.snd = new Audio("audio/start.wav");
      this.addButton((this.size.w - 200) / 2, 500, 200, 100, {
        normal: 'img/buttons/start.png',
        onhover: 'img/buttons/startHover.png'
      }, (function() {
        console.log('clicked');
        return this.snd.play();
      }));
    }

    Main.prototype.addButton = function(x, y, w, h, icon, onclick) {
      this.startButton = new Coffee2D.Image(icon.normal);
      this.startButton.setSize(w, h);
      this.startButton.setPosition(0, 0);
      this.startButtonH = new Coffee2D.Image(icon.onhover);
      this.startButtonH.setSize(w, h);
      this.startButtonH.setPosition(0, 0);
      this.startButtonH.hide();
      this.rec = new Rect(x, y, w, h);
      console.log(this.rec);
      this.rec.color = 'black';
      this.rec.addChild(this.startButton);
      this.rec.addChild(this.startButtonH);
      this.addListener('mouseMove', (function(evt) {
        if (this.rec.isPointInside(evt.x, evt.y)) {
          return this.startButtonH.show();
        } else {
          return this.startButtonH.hide();
        }
      }).bind(this));
      this.startButton.addListener('click', (function() {
        return Common.game.startBattle();
      }).bind(this));
      return this.addChild(this.rec);
    };

    return Main;

  })(Component);

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
