// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ProfilePanel = (function(_super) {

    __extends(ProfilePanel, _super);

    function ProfilePanel(panelPosition, panelSize) {
      this.panelPosition = panelPosition;
      this.panelSize = panelSize;
      ProfilePanel.__super__.constructor.call(this, this.panelPosition.x, this.panelPosition.y, this.panelSize.w, this.panelSize.h);
      this.init();
    }

    ProfilePanel.prototype.init = function() {
      this.profileFrame = new Coffee2D.Image('img/frame.png');
      this.profileFrame.setSize(this.size.w, this.size.h);
      return this.addChild(this.profileFrame);
    };

    ProfilePanel.prototype.updatePanel = function() {
      var unit;
      if (Common.selected instanceof Unit) {
        unit = Common.selected;
        this.removeChild(this.profileFrame);
        this.removeChild(this.profileImage);
        this.profileImage = new Coffee2D.Image(unit.iconFile);
        this.profileImage.setSize(this.size.w - 22, this.size.h - 20);
        this.profileImage.setPosition(11, 10);
        this.addChild(this.profileImage);
        this.addChild(this.profileFrame);
        return this.show();
      } else {
        return this.hide();
      }
    };

    return ProfilePanel;

  })(Component);

}).call(this);
