// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.StatsPanel = (function(_super) {

    __extends(StatsPanel, _super);

    function StatsPanel(panelPosition, panelSize, state) {
      this.panelPosition = panelPosition;
      this.panelSize = panelSize;
      this.state = state;
      StatsPanel.__super__.constructor.call(this, this.panelPosition.x, this.panelPosition.y, this.panelSize.w, this.panelSize.h);
      this.selectedUnit;
      this.init();
      this.poly = new Polygon([[0, 0], [0, this.size.h], [this.size.w, this.size.h], [this.size.w, 0]]);
      this.poly.color = 'rgba(240,20,50,0.4)';
      this.addChild(this.poly);
    }

    StatsPanel.prototype.init = function() {};

    StatsPanel.prototype.updatePanel = function() {
      var hpText, powerText, skillText, unit;
      if (Common.selected instanceof Unit) {
        unit = Common.selected;
        this.children = [];
        hpText = new Coffee2D.Text("HP: " + unit.curhp + "/" + unit.stats.hp, 'blue', '13px Verdana');
        hpText.setPosition(0, 20);
        powerText = new Coffee2D.Text("Evasion: " + unit.stats.evasion, 'black', '13px Verdana');
        powerText.setPosition(0, 40);
        skillText = new Coffee2D.Text("Skill: " + unit.stats.skill, 'red', '13px Verdana');
        skillText.setPosition(0, 60);
        this.addChild(hpText);
        this.addChild(powerText);
        this.addChild(skillText);
        return this.show();
      } else {
        return this.hide();
      }
    };

    return StatsPanel;

  })(Component);

}).call(this);
